fix: updated ci to handle pnpm

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -18,7 +18,34 @@ jobs:
         uses: actions/checkout@v4
       - name: Detect package manager
         id: detect-package-manager
-        run: "if [ -f \"${{ github.workspace }}/pnpm-lock.yaml\" ]; then\n  echo \"manager=pnpm\" >> $GITHUB_OUTPUT\n  echo \"command=install --frozen-lockfile\" >> $GITHUB_OUTPUT\n  echo \"runner=pnpm exec\" >> $GITHUB_OUTPUT\n  exit 0\nelif [ -f \"${{ github.workspace }}/yarn.lock\" ]; then\n  echo \"manager=yarn\" >> $GITHUB_OUTPUT\n  echo \"command=install\" >> $GITHUB_OUTPUT\n  echo \"runner=yarn\" >> $GITHUB_OUTPUT\n  exit 0\nelif [ -f \"${{ github.workspace }}/package.json\" ]; then\n  echo \"manager=npm\" >> $GITHUB_OUTPUT\n  echo \"command=ci\" >> $GITHUB_OUTPUT\n  echo \"runner=npx --no-install\" >> $GITHUB_OUTPUT\n  exit 0\nelse\n  echo \"Unable to determine package manager\"\n  exit 1\nfi\n  \n"
+        run: |
+          if [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
+            echo "manager=pnpm" >> $GITHUB_OUTPUT
+            echo "command=install --frozen-lockfile" >> $GITHUB_OUTPUT
+            echo "runner=pnpm exec" >> $GITHUB_OUTPUT
+            echo "Detected pnpm-lock.yaml, setting manager to pnpm."
+            exit 0
+          elif [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            echo "Detected yarn.lock, setting manager to yarn."
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            echo "Detected package.json, setting manager to npm."
+            exit 0
+          else
+            echo "Unable to determine package manager. No lock file or package.json found."
+            exit 1
+          fi
+      - name: Debug detected package manager
+        run: |
+          echo "Detected Manager: ${{ steps.detect-package-manager.outputs.manager }}"
+          echo "Install Command: ${{ steps.detect-package-manager.outputs.command }}"
+          echo "Runner: ${{ steps.detect-package-manager.outputs.runner }}"
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
